version: 2
jobs:
  build:
    branches:
      only:
        - opm

    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Build piMapper
          command: ./.circleci/run.sh
